### ISSUE TITLE
No binary or build instructions

### ISSUE THREAD

**Issue by abcbarryn** [gregharding/LCVersion#1]
Can you please provide an exe file or build instructions? I am using a Mac and don't even have a Windows handy to build on. You can post it as an attachment to a "release".

**Comment by gregharding** [comment]
hey Barry, I made this tool on a Mac in Visual Studio for Mac and ran it from the commandline using Mono. If you load up the .sln you should be able to build it pretty easily from the IDE. I don't have a Windows dev machine handy to make a windows .exe but if you want a Mac build of the .exe to run in Mono I will find some time to upload or send it to you.
